server:
  port: 8081

spring:
  application:
    name: USER-SERVICE
  config:
    import: "optional:configserver:"





#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    eureka-server-port: http://localhost:8671/eureka/
#  instance:
#    hostname: localhost


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    server-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost